version: "3.8"

services:
  db:
    image: postgres:${POSTGRES_VERSION}-bookworm
    container_name: db
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment:
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tty: true
    restart: always
    user: root
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - ${PGWEB_HOST_PORT}:${PGWEB_PORT}
    environment:
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    restart: always
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
